import {
  boolean,
  index,
  integer,
  pgTable,
  text,
  timestamp,
  unique,
} from "drizzle-orm/pg-core";

// ============================================================
// Branded types — prevent ID mix-ups at the TypeScript level
// Declared once in packages/domain/src/ids.ts. Imported here (for local use
// in this file's own branded column-type annotations below) AND
// re-exported (not merely imported — DR-09) so every existing
// `import type { ... } from "@/db/schema"` consumer keeps resolving
// unchanged. `export ... from` alone does not create a local binding per ES
// module semantics, so both statements are required.
// ============================================================

import type { CardId, DeckId, RecallEventId, UserId } from "@leocards/domain";

export type {
  CardId,
  DeckId,
  RecallDirection,
  RecallEventId,
  UserId,
} from "@leocards/domain";

// ============================================================
// Better Auth tables — must match Better Auth's expected shape
// Generated by inspecting @better-auth/core/db getAuthTables
// ============================================================

export const user = pgTable("user", {
  id: text("id").primaryKey().$type<UserId>(),
  name: text("name").notNull(),
  email: text("email").notNull().unique(),
  emailVerified: boolean("emailVerified").notNull().default(false),
  image: text("image"),
  createdAt: timestamp("createdAt").notNull().defaultNow(),
  updatedAt: timestamp("updatedAt").notNull().defaultNow(),
  nativeLanguage: text("nativeLanguage").notNull().default("en"),
});

export const session = pgTable(
  "session",
  {
    id: text("id").primaryKey(),
    expiresAt: timestamp("expiresAt").notNull(),
    token: text("token").notNull().unique(),
    createdAt: timestamp("createdAt").notNull().defaultNow(),
    updatedAt: timestamp("updatedAt").notNull().defaultNow(),
    ipAddress: text("ipAddress"),
    userAgent: text("userAgent"),
    userId: text("userId")
      .notNull()
      .references(() => user.id, { onDelete: "cascade" }),
  },
  (table) => [index("session_userId_idx").on(table.userId)],
);

export const account = pgTable("account", {
  id: text("id").primaryKey(),
  accountId: text("accountId").notNull(),
  providerId: text("providerId").notNull(),
  userId: text("userId")
    .notNull()
    .references(() => user.id, { onDelete: "cascade" }),
  accessToken: text("accessToken"),
  refreshToken: text("refreshToken"),
  idToken: text("idToken"),
  accessTokenExpiresAt: timestamp("accessTokenExpiresAt"),
  refreshTokenExpiresAt: timestamp("refreshTokenExpiresAt"),
  scope: text("scope"),
  password: text("password"),
  createdAt: timestamp("createdAt").notNull().defaultNow(),
  updatedAt: timestamp("updatedAt").notNull().defaultNow(),
});

export const verification = pgTable("verification", {
  id: text("id").primaryKey(),
  identifier: text("identifier").notNull(),
  value: text("value").notNull(),
  expiresAt: timestamp("expiresAt").notNull(),
  createdAt: timestamp("createdAt").notNull().defaultNow(),
  updatedAt: timestamp("updatedAt").notNull().defaultNow(),
});

// ============================================================
// App tables — defined in Phase 1, populated in later phases
// ============================================================

export const decks = pgTable(
  "decks",
  {
    id: text("id").primaryKey().$type<DeckId>(),
    userId: text("userId")
      .notNull()
      .references(() => user.id, { onDelete: "cascade" }),
    language: text("language").notNull(), // "fr" | "es" | "en"
    name: text("name").notNull(),
    createdAt: timestamp("createdAt").notNull().defaultNow(),
    updatedAt: timestamp("updatedAt").notNull().defaultNow(),
  },
  (table) => [index("decks_userId_idx").on(table.userId)],
);

export const cards = pgTable(
  "cards",
  {
    id: text("id").primaryKey().$type<CardId>(),
    deckId: text("deckId")
      .notNull()
      .references(() => decks.id, { onDelete: "cascade" }),
    front: text("front").notNull(), // word in native language
    back: text("back").notNull(), // translated word
    source: text("source").notNull(), // "manual" | "wordlist"
    recallCount: integer("recallCount").notNull().default(0),
    masteryRound: integer("masteryRound").notNull().default(0), // 0=new, 1=round1done, 2=round2done, 3=learned
    cooldownUntil: timestamp("cooldownUntil"), // null = available now
    lastStudiedAt: timestamp("lastStudiedAt"),
    // Idempotency guard for POST /api/study/complete (WR-04): the commitId of the
    // study session whose grades were last applied to this card. The per-card
    // UPDATE is gated on this (apply only when lastCommitId differs), so a retried
    // batch never double-advances masteryRound or double-increments recallCount.
    // null = never committed against; legacy rows are null and apply on first write.
    lastCommitId: text("lastCommitId"),
    pausedAt: timestamp("pausedAt"), // null = active, non-null = paused at this instant
    createdAt: timestamp("createdAt").notNull().defaultNow(),
    updatedAt: timestamp("updatedAt").notNull().defaultNow(),
  },
  (table) => [index("cards_deckId_idx").on(table.deckId)],
);

export const recall_events = pgTable(
  "recall_events",
  {
    id: text("id").primaryKey().$type<RecallEventId>(),
    cardId: text("cardId")
      .notNull()
      .references(() => cards.id, { onDelete: "cascade" }),
    correct: boolean("correct").notNull(),
    direction: text("direction").notNull(), // "n2t" | "t2n"
    createdAt: timestamp("createdAt").notNull().defaultNow(),
  },
  (table) => [index("recall_events_cardId_idx").on(table.cardId)],
);

export const milestones_seen = pgTable(
  "milestones_seen",
  {
    id: text("id").primaryKey(),
    userId: text("userId")
      .notNull()
      .references(() => user.id, { onDelete: "cascade" }),
    milestone: text("milestone").notNull(), // "10" | "25" | "50" | "100"
    seenAt: timestamp("seenAt").notNull().defaultNow(),
  },
  (table) => [
    unique("milestones_seen_userId_milestone_unique").on(
      table.userId,
      table.milestone,
    ),
  ],
);

export const habitat_metadata = pgTable("habitat_metadata", {
  id: text("id").primaryKey(),
  userId: text("userId")
    .notNull()
    .unique()
    .references(() => user.id, { onDelete: "cascade" }),
  lastActivityAt: timestamp("lastActivityAt").notNull().defaultNow(),
  createdAt: timestamp("createdAt").notNull().defaultNow(),
});
